<a href="https://colab.research.google.com/github/amruthaduvvuri/Data-Science-Tasks/blob/main/LINEAR_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing necessary libraries to read the dataframe
#first of pandas
import pandas as pd

In [ ]:
#getting already present dataset from colab with the help of sklearn.datasets
from sklearn.datasets import load_diabetes

In [ ]:
#importing other libraries
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#if we load the datasets from this with load_diabets() we get key - value pairs
load_diabetes()
#our output is basically target

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [ ]:
 #saving this as dataframe df
 df = load_diabetes()

In [ ]:
dataset= pd.DataFrame(df.data)

In [ ]:
#giving column names from the dataset
dataset.columns = df.feature_names

In [ ]:
dataset.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [ ]:
#indepedent and dependent features
X = dataset
y = df.target

In [ ]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.30,random_state= 42)
#

In [ ]:
X_train

age       sex       bmi        bp        s1        s2        s3  \
225  0.030811  0.050680  0.032595  0.049415 -0.040096 -0.043589 -0.069172   
412  0.074401 -0.044642  0.085408  0.063187  0.014942  0.013091  0.015505   
118 -0.056370  0.050680 -0.010517  0.025315  0.023198  0.040022 -0.039719   
114  0.023546 -0.044642  0.110198  0.063187  0.013567 -0.032942 -0.024993   
364  0.001751  0.050680 -0.006206 -0.019442 -0.009825  0.004949 -0.039719   
..        ...       ...       ...       ...       ...       ...       ...   
106 -0.096328 -0.044642 -0.076264 -0.043542 -0.045599 -0.034821  0.008142   
270  0.005383  0.050680  0.030440  0.083844 -0.037344 -0.047347  0.015505   
348  0.030811 -0.044642 -0.020218 -0.005670 -0.004321 -0.029497  0.078093   
435 -0.012780 -0.044642 -0.023451 -0.040099 -0.016704  0.004636 -0.017629   
102 -0.092695 -0.044642  0.028284 -0.015999  0.036958  0.024991  0.056003   

           s4        s5        s6  
225  0.034309  0.063015  0.003064  
412 -0.002592  0.006207  0.085907  
118  0.034309  0.020609  0.056912  
114  0.020655  0.099241  0.023775  
364  0.034309  0.014821  0.098333  
..        ...       ...       ...  
106 -0.039493 -0.059471 -0.083920  
270 -0.039493  0.008641  0.015491  
348 -0.039493 -0.010903 -0.001078  
435 -0.002592 -0.038460 -0.038357  
102 -0.039493 -0.005142 -0.001078  

[309 rows x 10 columns]

In [ ]:
y_train

array([208., 261., 179., 258., 262.,  51., 237.,  71., 139., 268.,  69.,
       317., 249., 154., 192., 116.,  81., 122., 259., 191., 292.,  55.,
       107., 210.,  91., 253.,  85., 252.,  59.,  78., 200.,  78., 245.,
       175.,  42., 127.,  53.,  94., 104., 199., 265., 281., 248., 257.,
       215., 303., 170.,  59., 277., 209., 138., 198., 124.,  96., 288.,
       225., 265., 101.,  55., 198.,  51., 252.,  64., 220., 131., 212.,
       142., 103., 155., 121.,  86., 111.,  65., 131.,  51., 128., 141.,
        48., 109., 178.,  88.,  84., 216., 150.,  60.,  96., 190.,  74.,
       279., 182., 160., 245., 276., 174., 180., 150., 196., 138.,  97.,
       246., 321., 308., 109.,  69., 182., 258., 161., 178., 214.,  45.,
       150., 160.,  55., 197., 185., 268., 310., 123.,  68.,  72., 185.,
       144., 147., 168., 178., 246., 151., 127.,  83., 332., 152., 109.,
        90.,  66., 214.,  85., 129.,  89., 259., 229., 200.,  77.,  54.,
        31., 109., 206., 144., 118.,  83., 242., 25

In [ ]:
#normalizing and standardizing the dataset
from sklearn.preprocessing import StandardScaler

In [ ]:
#initialising standard scalar
scaler = StandardScaler()

In [ ]:
#fitting the data for tranformation fit_transform is used to learn the scaling or hyperparameters tuned on the training dataset
scaler.fit_transform(X_train)

array([[ 6.42054387e-01,  1.05661647e+00,  6.19059528e-01, ...,
         6.76301514e-01,  1.27560982e+00, -2.79646760e-04],
       [ 1.58492079e+00, -9.46417203e-01,  1.71984406e+00, ...,
        -8.48887236e-02,  8.94884476e-02,  1.72793733e+00],
       [-1.24367842e+00,  1.05661647e+00, -2.79540092e-01, ...,
         6.76301514e-01,  3.90205997e-01,  1.12306139e+00],
       ...,
       [ 6.42054387e-01, -9.46417203e-01, -4.81725006e-01, ...,
        -8.46078961e-01, -2.67756388e-01, -8.66904956e-02],
       [-3.00812016e-01, -9.46417203e-01, -5.49119978e-01, ...,
        -8.48887236e-02, -8.43116611e-01, -8.64388135e-01],
       [-2.02940042e+00, -9.46417203e-01,  5.29199566e-01, ...,
        -8.46078961e-01, -1.47469368e-01, -8.66904956e-02]])

In [ ]:
X_train = scaler.fit_transform(X_train)

In [ ]:
#transform is used to on the new dataset i.e the testing dataset to apply the same transformation on the data
X_train = scaler.transform(X_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
#importing linear regression model
from sklearn.linear_model import LinearRegression

In [ ]:
#cross validation - splits the training data into multi folds of test and train to check the different combo of the accuracies
from sklearn.model_selection import cross_val_score


In [ ]:
#creating a regression object
regression = LinearRegression()

In [ ]:
#calculating with hyperparameters - which is regression , X_train , y_train data
cross_val_score(regression,X_train , y_train,scoring='neg_mean_squared_error',cv=5)

array([-3097.67026247, -3326.50097129, -2828.96412737, -3054.21375091,
       -3531.95904446])

In [ ]:
#mse - mean squared error
mse =cross_val_score(regression,X_train , y_train,scoring='neg_mean_squared_error',cv=5)

In [ ]:
#taking mean or average
np.mean(mse)

np.float64(-3167.8616313016114)